// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210821001939_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 1,
                            Gender = "Female",
                            Name = "Egypt",
                            Species = " Chubby Kitty"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Gender = "Female",
                            Name = "Doja",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 45,
                            Gender = "Male",
                            Name = "John Cena",
                            Species = "WWE WRESTLER"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1000,
                            Gender = "Male",
                            Name = "Wooly",
                            Species = "Mammoth"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 3,
                            Gender = "Male",
                            Name = "Tiger",
                            Species = "Dangerous Kitty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
